contact_links:
  - name: Discord server
    url: https://discord.gg/fFPEFYUnVp
    about: You can also discuss bugs and features here.
  - name: Security policy
    url: https://github.com/sunset-vacation/.github/blob/main/SECURITY.md
    about: Please follow these procedures for security vulnerabilities.
